Basic Django Rest API
saadyousafarbi/auto-shop pull request #11
Opened 2017-08-18 11:34 UTC by saadyousafarbi

Basic Django API developed for model ```Profile``` with following functionality:

* API will be able to retrieve all Profiles within database for autoshop site.
* API will also have capability of editing profile with valid data provided.
* API will be exposed to only authenticated users.

2017-08-21 07:55 UTC, zubair-arbi requested changes

2017-08-21 07:55 UTC, zubair-arbi commented on autoshop/api/v1/views.py
> +from autoshop.api.v1.serializers import ProfileSerializer
ordering of imports

2017-08-21 07:55 UTC, zubair-arbi commented on autoshop/api/v1/serializers.py
> +class ProfileSerializer(serializers.ModelSerializer):
We might want to rename it to `UserProfileSerializer` for clarity of whose profile its is.

2017-08-21 07:55 UTC, zubair-arbi commented on autoshop/settings.py
> +    'rest_framework',
the third party apps should come before local apps

2017-08-21 07:55 UTC, zubair-arbi commented on autoshop/urls.py
> +from api.v1 import views
local imports at the end

2017-08-21 07:55 UTC, zubair-arbi commented on autoshop/urls.py
> +urlpatterns = format_suffix_patterns(urlpatterns)
What is the purpose of `format_suffix_patterns`?

2017-08-21 09:16 UTC, saadyousafarbi commented
I have made corrections and also shifted from APIView to using generic views from rest framework. Please have a look at changes.

2017-08-21 09:47 UTC, zubair-arbi requested changes

2017-08-21 09:47 UTC, zubair-arbi commented on autoshop/api/v1/serializers.py
> +        fields = '__all__'
I think we dont need time stamp model fields here. Also user should not be able to edit username which we use for login.

2017-08-21 09:47 UTC, zubair-arbi commented on autoshop/api/v1/views.py
> +class ProfileList(ListAPIView):
I think the `ModelViewSet` is more appropriate for our use case.

2017-08-21 09:47 UTC, zubair-arbi commented on autoshop/api/v1/views.py
> +class ProfileList(ListAPIView):
Please look into these resources:
* http://www.django-rest-framework.org/api-guide/routers/#routers
* http://www.django-rest-framework.org/api-guide/viewsets/#modelviewset

2017-08-21 10:43 UTC, saadyousafarbi commented on autoshop/api/v1/serializers.py
> +        fields = '__all__'
All important data is not present in Profile model. Username, email, password etc are present in Django's default User model and Profile model only has User ID associated with it other than profile information.

2017-08-21 10:44 UTC, saadyousafarbi commented on autoshop/api/v1/views.py
> +class ProfileList(ListAPIView):
How do we determine which approach is better than the other? They all seem to achieve the desired output.

2017-08-21 11:22 UTC, zubair-arbi commented on autoshop/api/v1/serializers.py
> +        fields = '__all__'
But user should be able to edit name (`first_name` and `last_name`).

2017-08-21 11:23 UTC, zubair-arbi commented on autoshop/api/v1/views.py
> +class ProfileList(ListAPIView):
Well its about what you want to do with end point. We want an endpoint for django model with the basic crud operations. Although we will not support the delete operation for now.

2017-08-21 11:40 UTC, zubair-arbi commented on autoshop/api/v1/views.py
> +class UserProfileViewSet(ModelViewSet):
implement actions provided by the `ModelViewSet`

2017-08-21 12:26 UTC, zubair-arbi commented on autoshop/api/v1/serializers.py
> +        fields = '__all__'
we still need to figure out how to include fields `first_name` and `last_name` with this API

2017-08-21 12:27 UTC, zubair-arbi commented on autoshop/api/v1/views.py
> +class UserProfileViewSet(ModelViewSet):
I am not seeing action for update

2017-08-22 09:08 UTC, zubair-arbi commented on autoshop/api/v1/serializers.py
> +        fields = '__all__'
Any follow up on this suggestion?

2017-08-22 09:24 UTC, zubair-arbi commented on autoshop/api/v1/views.py
> +        queryset = Profile.objects.all()
do we need this `queryset`  same as default `queryset`?

2017-08-22 09:31 UTC, saadyousafarbi commented on autoshop/api/v1/views.py
> +        queryset = Profile.objects.all()
yes, it is required in every action.

2017-08-22 10:08 UTC, saadyousafarbi commented on autoshop/api/v1/serializers.py
> +        fields = '__all__'
We would have to change the model

2017-08-22 10:55 UTC, zubair-arbi approved these changes
Rebase, squash and merge 👍

2017-08-22 11:08 UTC, saadyousafarbi commented
Rebased from 40d83256ecd8f4fe400aa75c135458661b860e8b

2017-08-22 11:08 UTC, merged