Autoshop Sign-In/ Sign-Up basic workflow.
saadyousafarbi/auto-shop pull request #2
Opened 2017-08-02 12:35 UTC by saadyousafarbi

A basic workflow for signup/signin for Autoshop website. User can login if they have an existing account and users can also register as a new account. Users are provided with their profile information as well.

2017-08-02 13:32 UTC, saadyousafarbi commented
@zubair-arbi
Please do review the code and I will look into all the problems you point out and correct them.

2017-08-03 08:29 UTC, zubair-arbi requested changes
Please fix these suggestions.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/autoshop/settings.py
> +    'login_signup.apps.LoginSignupConfig',
Lets rename this app to `core` and move all site wide logic here.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/apps.py
> +class LoginSignupConfig(AppConfig):
`LoginSignup` -> `Logistration`

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/migrations/0002_auto_20170802_0614.py
> +from __future__ import unicode_literals
Please combine both migrations. Always try to have single migration for a PR.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/migrations/0003_auto_20170802_0621.py
> +# Generated by Django 1.11.3 on 2017-08-02 06:21
Remove this migration. Generate a single migration as this will be our first database change.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/migrations/0004_auto_20170802_0623.py
> +from django.db import migrations
remove

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/models.py
> +class User(models.Model):
Use django's default user model

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +    user_information = User.objects.get(username = username)
remove spaces inside get

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +    return render(request, 'profile.html',  {'user_info_dict':user_info_dict})
only pass `context` variable.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +    user_info_dict = {
add this dict in `context` variable

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +    return render(request, 'profile.html',  {'user_info_dict':user_info_dict})
Example:
```
return render(request, 'profile.html', context)
```

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +    This view directs user to success page in case of successful signup/login.
be consistent with either using `signin` or `login`

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/urls.py
> +    url(r'^$', views.welcome, name='welcome'),
Replace `welcome` with `home`, `dashboard` or `profile`.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/urls.py
> +    url(r'^signin', views.sign_in, name='sign_in'),
I would recommend using `login`, `logout` and `register`.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +from .forms import SignupForm, SigninForm
Always try to use full path during imports.

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +from django.contrib.auth.models import User
combine django import and local imports

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +    return render(request, 'autoshop_welcome.html')
No need to namespace every template with the app name

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +        form (POST), user registration takes place. If user is visiting
fix indentation

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +                User.objects.create_user(
Use `get_or_create` it will remove the exception handling

2017-08-03 08:29 UTC, zubair-arbi commented on autoshop/login_signup/views.py
> +        a user is submitting (POST) his credentials or whether a user is
indentation

2017-08-04 10:17 UTC, zubair-arbi commented
@saadyousafarbi Please remove you own `User` model and use django's authentication mechanism. Follow this tutorial https://docs.djangoproject.com/en/1.11/topics/auth/default/

2017-08-04 11:15 UTC, zubair-arbi requested changes
Please fix these suggestions.

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/forms.py
> +    first_name = forms.CharField(max_length=100)
do these lengths comply with lengths enforced in dafault django's `User` model?

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +def home(request):
`index`

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +    return render(request, 'home.html')
base.html

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +                User.objects.create_user(
What if a user already exists?

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +            except IntegrityError:
can we avoid this exception?

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +            if user is not None:
```python 
if not user:
    return redirect('failure.html')

login(request, user)
return redirect('success.html')

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +def success(request):
Only logged in user's should access this page

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +    This view directs user to success page in case of successful register/
update docstring

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +    This view directs user to failure page in case of wrong register/login.
update docstring

2017-08-04 11:15 UTC, zubair-arbi commented on autoshop/core/views.py
> +def profile(request):
For only logged in users

2017-08-04 11:18 UTC, saadyousafarbi commented on autoshop/core/views.py
> +                User.objects.create_user(
An exception is raised if a user exists.

2017-08-04 11:19 UTC, saadyousafarbi commented on autoshop/core/views.py
> +            except IntegrityError:
No. I tried to create the user with get_or_create to avoid exception but that causes login problems.

2017-08-04 11:49 UTC, zubair-arbi commented on autoshop/core/views.py
> +                User.objects.create_user(
do it without raising any exception

2017-08-04 11:49 UTC, zubair-arbi commented on autoshop/core/views.py
> +            except IntegrityError:
What kind of problems?

2017-08-04 13:07 UTC, zubair-arbi commented
@saadyousafarbi lgtm 👍 
Squash the changes and merge

2017-08-04 13:11 UTC, merged