Basic profile editing feature added with new model Profile.
saadyousafarbi/auto-shop pull request #3
Opened 2017-08-07 12:31 UTC by saadyousafarbi

User is now able to view more information of his/her profile than before. User is also now able to edit any profile information about himself/herself as he/she wishes.

2017-08-07 12:39 UTC, saadyousafarbi commented
@zubair-arbi Please review changes.

2017-08-08 07:34 UTC, zubair-arbi requested changes
I have gone through changes and added my initial feedback.

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/models.py
> +        help_text='Verified mobile number with country code', max_length=12, null=True
lets set it to 15 length for now

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/models.py
> +    objects = models.Manager()
please remove this, we dont need it

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/templates/editprofile.html
> +                            {% csrf_token %}
please make sure we have indented all files properly

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/templates/profile.html
> +    Bio: {{user_info_dict.bio}} <br>
`{{user_info_dict.bio}}` -> `{{ user_info_dict.bio }}` notice spaces inside curly brackets

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/templates/profile.html
> +    <a href="/editprofile">Edit profile</a>
use django's reverse url, avoid using hard coded values

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/urls.py
> +    url(r'^editprofile', views.edit_profile, name='edit_profile'),
this url should be `/profile/edit`

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/views.py
> +from .forms import SignupForm, SigninForm, EditProfileForm
use absolute urls

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/views.py
> +            return render(request, 'editprofile.html', context)
after updating profile, the user should be redirected to profile view page.

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/views.py
> +    This view directs user to edit page where user can change profile
update docstring as this will not always redirect user to profile edit page

2017-08-08 07:34 UTC, zubair-arbi commented on autoshop/core/forms.py
> +        all fields from Profile model
remove it as it is not providing any useful information.  we can clearly see that its a `Profile` model form

2017-08-08 11:34 UTC, zubair-arbi approved these changes
Changes look good now 👍

2017-08-08 11:34 UTC, merged