Working on adding bootstrap to project.
saadyousafarbi/auto-shop pull request #6
Opened 2017-08-11 06:15 UTC by saadyousafarbi

Started by adding basic CSS to registration form.

2017-08-11 10:37 UTC, zubair-arbi requested changes
Please fix these suggestions

2017-08-11 10:37 UTC, zubair-arbi commented on autoshop/core/forms.py
> +            'username': 'Enter username',
We need to also tell users that it cannot be change later.
Check `edX` register for example: https://courses.edx.org/register

2017-08-11 10:37 UTC, zubair-arbi commented on autoshop/core/templates/base.html
> +{% extends "basic.html" %}
rename this `basic.html` to `base.html`

2017-08-11 10:37 UTC, zubair-arbi commented on autoshop/core/templates/basic.html
> +            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
We should add this file as project static

2017-08-11 10:37 UTC, zubair-arbi commented on autoshop/core/templates/register.html
>              {{form.as_table}}
indentation

2017-08-11 10:37 UTC, zubair-arbi commented on autoshop/core/templates/register.html
> +{% load staticfiles %}
why we are using this template tag?

2017-08-11 10:41 UTC, zubair-arbi commented on autoshop/core/static/css/core.css
> +    position: relative;
We should be getting this file from project static folder

2017-08-15 09:18 UTC, zubair-arbi approved these changes
LGTM 👍 . Rebase, squash and add comment.

2017-08-15 09:19 UTC, zubair-arbi commented
Also please add screenshots of logistration pages and profile edit page in the PR description.

2017-08-15 09:51 UTC, saadyousafarbi commented
Rebased from commit a04464667e1cd8bb22251c93c3d56532943b62d9

2017-08-15 09:52 UTC, merged