Using Django views instead of custom pages to handle responses.
saadyousafarbi/auto-shop pull request #7
Opened 2017-08-15 11:01 UTC by saadyousafarbi

Removing the extra failure.html and success.html and replacing them with built-in django templates. Also introducing dashboard.html where user is redirected after successful login.

2017-08-15 12:00 UTC, zubair-arbi requested changes
Can you please read the django docs on `Built-in` views again? https://docs.djangoproject.com/en/1.11/ref/views/#module-django.views
We need to introduce 404 and 500 pages with our own site wise styling. Please note the parameters here:
```
defaults.page_not_found(request, exception, template_name='404.html')

defaults.server_error(request, template_name='500.html')
```

2017-08-15 12:00 UTC, zubair-arbi commented on autoshop/autoshop/settings.py
> +DEBUG = False
This is the right choice. But for local development we need to run django in debug mode. Please create a `private.py` settings file and override this value there

2017-08-15 12:00 UTC, zubair-arbi commented on autoshop/core/templates/dashboard.html
> +    Dashboard
Remove this file all together. Redirect the user to `index` page which will serve as `homepage`.

2017-08-15 12:00 UTC, zubair-arbi commented on autoshop/core/urls.py
> +    url(r'^dashboard/$', views.dashboard, name='dashboard'),
No need

2017-08-15 12:00 UTC, zubair-arbi commented on autoshop/core/views.py
> +        return Http404('Form is invalid:' + form.errors)
Revert this. We will redirect the user to profile edit page with form error message in our separate story.

2017-08-15 12:00 UTC, zubair-arbi commented on autoshop/core/views.py
> +                raise PermissionDenied
Again we will redirect the user to login page with error message. We can do that with django messages.

2017-08-15 12:00 UTC, zubair-arbi commented on autoshop/core/views.py
> +        return Http404('Form is invalid:' + form.errors)
404 is for `page not found` error. Redirect user to previous page

2017-08-16 08:06 UTC, zubair-arbi requested changes
Please add `404.html` and `500.html`

2017-08-16 08:06 UTC, zubair-arbi commented on autoshop/core/templates/login.html
> +{% for message in messages %}
indentation

2017-08-16 08:06 UTC, zubair-arbi commented on autoshop/core/urls.py
> +    url(r'^dashboard/$', views.dashboard, name='dashboard'),
remove this page as our requirement for now is to redirect user to homepage, i.e. `index`.

2017-08-16 08:06 UTC, zubair-arbi commented on autoshop/core/views.py
> +def dashboard(request):
remove this view

2017-08-16 08:06 UTC, zubair-arbi commented on autoshop/core/views.py
> +        messages.error(request, 'Form is invalid'+form.errors)
nit: spaces around the operator

2017-08-16 08:06 UTC, zubair-arbi commented on autoshop/core/views.py
> +        messages.error(request, 'Form is invalid. Please try again.'+form.errors)
nit: spaces around operator

2017-08-16 09:20 UTC, zubair-arbi commented on autoshop/core/templates/dashboard.html
> +<a href="/profile">profile</a>
always use reverse urls.

2017-08-16 10:59 UTC, zubair-arbi approved these changes
Nice work 👍

2017-08-17 05:27 UTC, saadyousafarbi commented
Rebased from e8075809ea6d861f8f44d0b1ca68103782a2c090

2017-08-17 05:27 UTC, merged