Adding custom context processor
saadyousafarbi/auto-shop pull request #9
Opened 2017-08-17 11:13 UTC by saadyousafarbi

Adding custom context processor which contain information (URL) of Pakwheels website.

* Custom processor will return dictionary containing URL of Pakwheels website.
* This URL will be provided to all templates available in the footer of the template.

2017-08-17 12:04 UTC, zubair-arbi requested changes
Please fix these suggstions

2017-08-17 12:04 UTC, zubair-arbi commented on autoshop/core/templates/base.html
> +            Related Website:
See djangos `trans` template tag

2017-08-17 12:04 UTC, zubair-arbi commented on autoshop/core/templates/base.html
> +            <a href='{{PakWheels_site}}' target="_blank">Visit Site</a>
need spaces

2017-08-17 12:04 UTC, zubair-arbi commented on autoshop/analytics/processor.py
> +    related_site = {'PakWheels_site': 'https://www.pakwheels.com/'}
this is not what we wanted. Just pass django's settings and site object directly

2017-08-17 12:04 UTC, zubair-arbi commented on autoshop/analytics/processor.py
> +def related_website(request):
This should be in `autoshop` app or in `core` app as its a site wide context processor.
Also rename it to `site_processor`.

2017-08-18 06:22 UTC, zubair-arbi requested changes
Please update the PR description and mention what variable will be provided site wide in request context.

2017-08-18 06:22 UTC, zubair-arbi commented on autoshop/core/site_processor.py
> +def setting_and_site_context(request):
rename the file to `context_processors` and rename this method to `site_processor`

2017-08-18 06:22 UTC, zubair-arbi commented on autoshop/core/templates/base.html
> +
remove this change

2017-08-18 06:22 UTC, zubair-arbi commented on autoshop/core/site_processor.py
> +def setting_and_site_context(request):
Also add docstring like:
```
"""
Provide site object and common project settings across all project in context.
"""
```

2017-08-18 07:19 UTC, zubair-arbi commented
Please squash your commits into a single one. Then wait for my PR https://github.com/saadyousafarbi/auto-shop/pull/10 to merge, that PR will change the project structure a bit.
After that update your local master and rebase your branch onto it.

2017-08-18 07:59 UTC, zubair-arbi approved these changes
LGTM 👍

2017-08-18 08:00 UTC, saadyousafarbi commented
Last commit 3bfbfa8eaaa4e2c5d9326754a640a8adf40c0943

2017-08-18 08:00 UTC, merged